### ISSUE TITLE
Dockerfile needs to use gvt as well

### ISSUE THREAD

**Issue by jasonrichardsmith** [microservices-demo/catalogue#16]
Nothing like Glide is being used for package management, this needs to be updated.

**Comment by vlal** [comment]
Does gvt count?

**Comment by jasonrichardsmith** [comment]
Yes it does sorry.  We have been using glide and the Docker file was just using go gets.

https://github.com/microservices-demo/catalogue/blob/master/docker/catalogue/Dockerfile#L7

So I think we can just update that.  This being a demo app, I like the idea of using different tools.

**Comment by vlal** [comment]
cool! seems I forgot to update the dockerfile. I'll use this ticket to track that
