### ISSUE TITLE
Use glide for golang vendoring

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/catalogue#7]
Already had a few issues with out of date packages.

**Comment by peterbourgon** [comment]
Note from the peanut gallery. If you're set on Glide then absolutely don't let me derail you. But if you just picked it out of a hat, then based on my experience with it I'd suggest you take a look at a lighter-weight alternative. I like [gvt](https://github.com/FiloSottile/gvt) and [govendor](https://github.com/kardianos/govendor) is quite nice too.

**Comment by vlal** [comment]
Fixed with #15
